[package]
name = "frustoz-io"
version = "0.1.0"
authors = ["Aleksei Sukontsev <aleksei.sukontsev@gmail.com>"]
edition = "2018"

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
xml-rs = "0.8.0"
image = "0.19.0"
frustoz-core = { version = "0.1.0", path = "../frustoz-core"}
