[package]
name = "frustoz-core"
version = "0.1.1"
authors = ["Aleksei Sukontsev <aleksei.sukontsev@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
log = { version = "0.4.21", features = ["release_max_level_info"] }
rayon = "1.10.0"
rand = "0.5.6"